### ISSUE TITLE
errors with phylo diversity

### ISSUE THREAD

**Issue by jaytlennon** [LennonLab/eDNA#30]
Starting on line 318 of diversity.Rmd, I'm not able to to run the phylo analyses. 

> OTU.tre.rooted <- midpoint(OTU.tre)
> Error: could not find function "midpoint"
> 
> sum(colnames(OTU) %in% OTU.tre$tip.label) == length(colnames(OTU) %in% OTU.tre$tip.label)
> [1] FALSE
> 
> OTU.tre.rooted <- midpoint(OTU.tre)
> Error: could not find function "midpoint"

But things below that work!

**Comment by mmuscarella** [comment]
I forgot to uncomment phangorn
