### ISSUE TITLE
rarefy

### ISSUE THREAD

**Issue by jaytlennon** [LennonLab/eDNA#35]
@mmuscarella 

I'm getting an error when I run the following code in diversity.Rmd:

`rarefy(OTU, sample, se = FALSE, MARGIN = 1)`

Error in sample > minsample : 
  comparison (6) is possible only for atomic and list types

I'm guessing maybe I don't have a package installed or dependency. Not sure whether or not this is important.

**Comment by mmuscarella** [comment]
I forgot to actually define the sample size. I fixed it. Making the multipanel figure now and will push in a little bit.
