### ISSUE TITLE
Centroid issue: diversity2.Rmd (and diversity.Rmd)

### ISSUE THREAD

**Issue by jaytlennon** [LennonLab/eDNA#74]
### Something wrong here i.e., line ~1403 **and** 1636
centroid.div$prop <- NA
for (i in 1:length(centroid.div$prop)){
  centroid.div$prop[i] <- eDNA.prop$prop[which(eDNA.prop$sample.number ==
                                                 centroid.div$qPCR.match[i])]
}
####

**Comment by mmuscarella** [comment]
I'm assuming we fixed this because I don't have any errors at this point
